### ISSUE TITLE
Implement XOR Linked List

### ISSUE THREAD

**Issue by pvgupta24** [pvgupta24/CSE-Labs#1]
Implement XOR Linked List in /DSA/Lab 4/XOR.c with

- [ ] Adding node at nth position
- [ ] Deleting node at nth position

**Comment by platipo** [comment]
Working on this!

**Comment by platipo** [comment]
It is already present as [XorLL.c](https://github.com/pvgupta24/CSE-Labs/blob/master/DSA/Lab%204/XorLL.c). Isn't it?

**Comment by platipo** [comment]
It is already present as [XorLL.c](https://github.com/pvgupta24/CSE-Labs/blob/master/DSA/Lab%204/XorLL.c). Isn't it?

**Comment by pvgupta24** [comment]
@platipo it has bugs.

**Comment by platipo** [comment]
Random question: why is the PR still open?

**Comment by pvgupta24** [comment]
@platipo merged it. :)
